routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Cursos
    Route::delete('cursos/destroy', 'CursosController@massDestroy')->name('cursos.massDestroy');
    Route::resource('cursos', 'CursosController');

    // Materia
    Route::delete('materia/destroy', 'MateriaController@massDestroy')->name('materia.massDestroy');
    Route::resource('materia', 'MateriaController');

    // Tareas
    Route::delete('tareas/destroy', 'TareasController@massDestroy')->name('tareas.massDestroy');
    Route::post('tareas/media', 'TareasController@storeMedia')->name('tareas.storeMedia');
    Route::post('tareas/ckmedia', 'TareasController@storeCKEditorImages')->name('tareas.storeCKEditorImages');
    Route::get('tareas/mostrarcursos', 'TareasController@showCursos')->name('tareas.mostrarcursos');
    Route::resource('tareas', 'TareasController');
    

    // Tarea Estudiante
    Route::delete('tarea-estudiantes/destroy', 'TareaEstudianteController@massDestroy')->name('tarea-estudiantes.massDestroy');
    Route::resource('tarea-estudiantes', 'TareaEstudianteController');

    // Estudiante
    Route::delete('estudiantes/destroy', 'EstudianteController@massDestroy')->name('estudiantes.massDestroy');
    Route::resource('estudiantes', 'EstudianteController');

    // Representante
    Route::delete('representantes/destroy', 'RepresentanteController@massDestroy')->name('representantes.massDestroy');
    Route::resource('representantes', 'RepresentanteController');

    // Detalle Tarea
    Route::delete('detalle-tareas/destroy', 'DetalleTareaController@massDestroy')->name('detalle-tareas.massDestroy');
    Route::resource('detalle-tareas', 'DetalleTareaController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/TareaEstudiante.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TareaEstudiante extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'tarea_estudiantes';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'tarea_id',
        'valor',
        'estudiante_id',
        'profesor_id',
        'curso_id',
        'created_at',
        'materia_id',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function tarea()
    {
        return $this->belongsTo(Tarea::class, 'tarea_id');
    }

    public function estudiante()
    {
        return $this->belongsTo(User::class, 'estudiante_id');
    }

    public function profesor()
    {
        return $this->belongsTo(User::class, 'profesor_id');
    }

    public function curso()
    {
        return $this->belongsTo(Curso::class, 'curso_id');
    }

    public function materia()
    {
        return $this->belongsTo(Materium::class, 'materia_id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/TareaEstudianteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTareaEstudianteRequest;
use App\Http\Requests\StoreTareaEstudianteRequest;
use App\Http\Requests\UpdateTareaEstudianteRequest;
use App\Models\Tarea;
use App\Models\TareaEstudiante;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TareaEstudianteController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('tarea_estudiante_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tareaEstudiantes = TareaEstudiante::with(['tarea', 'estudiante', 'profesor', 'curso', 'materia', 'created_by'])->get();

        return view('admin.tareaEstudiantes.index', compact('tareaEstudiantes'));
    }

    public function create()
    {
        abort_if(Gate::denies('tarea_estudiante_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tareas = Tarea::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.tareaEstudiantes.create', compact('tareas'));
    }

    public function store(StoreTareaEstudianteRequest $request)
    {
        $tareaEstudiante = TareaEstudiante::create($request->all());

        return redirect()->route('admin.tarea-estudiantes.index');
    }

    public function edit(TareaEstudiante $tareaEstudiante)
    {
        abort_if(Gate::denies('tarea_estudiante_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tareas = Tarea::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $tareaEstudiante->load('tarea', 'estudiante', 'profesor', 'curso', 'materia', 'created_by');

        return view('admin.tareaEstudiantes.edit', compact('tareas', 'tareaEstudiante'));
    }

    public function update(UpdateTareaEstudianteRequest $request, TareaEstudiante $tareaEstudiante)
    {
        $tareaEstudiante->update($request->all());

        return redirect()->route('admin.tarea-estudiantes.index');
    }

    public function show(TareaEstudiante $tareaEstudiante)
    {
        abort_if(Gate::denies('tarea_estudiante_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tareaEstudiante->load('tarea', 'estudiante', 'profesor', 'curso', 'materia', 'created_by');

        return view('admin.tareaEstudiantes.show', compact('tareaEstudiante'));
    }

    public function destroy(TareaEstudiante $tareaEstudiante)
    {
        abort_if(Gate::denies('tarea_estudiante_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tareaEstudiante->delete();

        return back();
    }

    public function massDestroy(MassDestroyTareaEstudianteRequest $request)
    {
        TareaEstudiante::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/tareaEstudiantes/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.tareaEstudiante.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.tarea-estudiantes.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('tarea') ? 'has-error' : '' }}">
                            <label class="required" for="tarea_id">{{ trans('cruds.tareaEstudiante.fields.tarea') }}</label>
                            <select class="form-control select2" name="tarea_id" id="tarea_id" required>
                                @foreach($tareas as $id => $entry)
                                    <option value="{{ $id }}" {{ old('tarea_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('tarea'))
                                <span class="help-block" role="alert">{{ $errors->first('tarea') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.tareaEstudiante.fields.tarea_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('valor') ? 'has-error' : '' }}">
                            <label for="valor">{{ trans('cruds.tareaEstudiante.fields.valor') }}</label>
                            <input class="form-control" type="text" name="valor" id="valor" value="{{ old('valor', '') }}">
                            @if($errors->has('valor'))
                                <span class="help-block" role="alert">{{ $errors->first('valor') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.tareaEstudiante.fields.valor_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/tareaEstudiantes/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.tareaEstudiante.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.tarea-estudiantes.update", [$tareaEstudiante->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('tarea') ? 'has-error' : '' }}">
                            <label class="required" for="tarea_id">{{ trans('cruds.tareaEstudiante.fields.tarea') }}</label>
                            <select class="form-control select2" name="tarea_id" id="tarea_id" required>
                                @foreach($tareas as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('tarea_id') ? old('tarea_id') : $tareaEstudiante->tarea->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('tarea'))
                                <span class="help-block" role="alert">{{ $errors->first('tarea') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.tareaEstudiante.fields.tarea_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('valor') ? 'has-error' : '' }}">
                            <label for="valor">{{ trans('cruds.tareaEstudiante.fields.valor') }}</label>
                            <input class="form-control" type="text" name="valor" id="valor" value="{{ old('valor', $tareaEstudiante->valor) }}">
                            @if($errors->has('valor'))
                                <span class="help-block" role="alert">{{ $errors->first('valor') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.tareaEstudiante.fields.valor_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/tareaEstudiantes/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('tarea_estudiante_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.tarea-estudiantes.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.tareaEstudiante.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.tareaEstudiante.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-TareaEstudiante">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.tarea') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.valor') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.estudiante') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.profesor') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.curso') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.materia') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tareaEstudiantes as $key => $tareaEstudiante)
                                    <tr data-entry-id="{{ $tareaEstudiante->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->tarea->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->valor ?? '' }}
                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->estudiante->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->profesor->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->curso->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $tareaEstudiante->materia->nombre ?? '' }}
                                        </td>
                                        <td>
                                            @can('tarea_estudiante_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.tarea-estudiantes.show', $tareaEstudiante->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('tarea_estudiante_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.tarea-estudiantes.edit', $tareaEstudiante->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('tarea_estudiante_delete')
                                                <form action="{{ route('admin.tarea-estudiantes.destroy', $tareaEstudiante->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('tarea_estudiante_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tarea-estudiantes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-TareaEstudiante:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/tareaEstudiantes/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('cruds.tareaEstudiante.title') }}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.tarea-estudiantes.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.id') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->id }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.tarea') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->tarea->nombre ?? '' }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.valor') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->valor }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.estudiante') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->estudiante->name ?? '' }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.profesor') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->profesor->name ?? '' }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.curso') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->curso->nombre ?? '' }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.tareaEstudiante.fields.materia') }}
                                    </th>
                                    <td>
                                        {{ $tareaEstudiante->materia->nombre ?? '' }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.tarea-estudiantes.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection