routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Cursos
    Route::delete('cursos/destroy', 'CursosController@massDestroy')->name('cursos.massDestroy');
    Route::resource('cursos', 'CursosController');

    // Materia
    Route::delete('materia/destroy', 'MateriaController@massDestroy')->name('materia.massDestroy');
    Route::resource('materia', 'MateriaController');

    // Tareas
    Route::delete('tareas/destroy', 'TareasController@massDestroy')->name('tareas.massDestroy');
    Route::post('tareas/media', 'TareasController@storeMedia')->name('tareas.storeMedia');
    Route::post('tareas/ckmedia', 'TareasController@storeCKEditorImages')->name('tareas.storeCKEditorImages');
    Route::get('tareas/mostrarcursos', 'TareasController@showCursos')->name('tareas.mostrarcursos');
    Route::resource('tareas', 'TareasController');
    

    // Tarea Estudiante
    Route::delete('tarea-estudiantes/destroy', 'TareaEstudianteController@massDestroy')->name('tarea-estudiantes.massDestroy');
    Route::resource('tarea-estudiantes', 'TareaEstudianteController');

    // Estudiante
    Route::delete('estudiantes/destroy', 'EstudianteController@massDestroy')->name('estudiantes.massDestroy');
    Route::resource('estudiantes', 'EstudianteController');

    // Representante
    Route::delete('representantes/destroy', 'RepresentanteController@massDestroy')->name('representantes.massDestroy');
    Route::resource('representantes', 'RepresentanteController');

    // Detalle Tarea
    Route::delete('detalle-tareas/destroy', 'DetalleTareaController@massDestroy')->name('detalle-tareas.massDestroy');
    Route::resource('detalle-tareas', 'DetalleTareaController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Http/Controllers/Admin/MateriaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMateriumRequest;
use App\Http\Requests\StoreMateriumRequest;
use App\Http\Requests\UpdateMateriumRequest;
use App\Models\Curso;
use App\Models\Materium;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class MateriaController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('materium_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $materia = Materium::with(['curso', 'created_by'])->get();

        return view('admin.materia.index', compact('materia'));
    }

    public function create()
    {
        abort_if(Gate::denies('materium_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $cursos = Curso::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.materia.create', compact('cursos'));
    }

    public function store(StoreMateriumRequest $request)
    {
        $materium = Materium::create($request->all());

        return redirect()->route('admin.materia.index');
    }

    public function edit(Materium $materium)
    {
        abort_if(Gate::denies('materium_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $cursos = Curso::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $materium->load('curso', 'created_by');

        return view('admin.materia.edit', compact('cursos', 'materium'));
    }

    public function update(UpdateMateriumRequest $request, Materium $materium)
    {
        $materium->update($request->all());

        return redirect()->route('admin.materia.index');
    }

    public function show(Materium $materium)
    {
        abort_if(Gate::denies('materium_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $materium->load('curso', 'created_by');

        return view('admin.materia.show', compact('materium'));
    }

    public function destroy(Materium $materium)
    {
        abort_if(Gate::denies('materium_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $materium->delete();

        return back();
    }

    public function massDestroy(MassDestroyMateriumRequest $request)
    {
        Materium::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/materia/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.materium.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.materia.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('nombre') ? 'has-error' : '' }}">
                            <label class="required" for="nombre">{{ trans('cruds.materium.fields.nombre') }}</label>
                            <input class="form-control" type="text" name="nombre" id="nombre" value="{{ old('nombre', '') }}" required>
                            @if($errors->has('nombre'))
                                <span class="help-block" role="alert">{{ $errors->first('nombre') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.materium.fields.nombre_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('curso') ? 'has-error' : '' }}">
                            <label for="curso_id">{{ trans('cruds.materium.fields.curso') }}</label>
                            <select class="form-control select2" name="curso_id" id="curso_id">
                                @foreach($cursos as $id => $entry)
                                    <option value="{{ $id }}" {{ old('curso_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('curso'))
                                <span class="help-block" role="alert">{{ $errors->first('curso') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.materium.fields.curso_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/materia/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.materium.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.materia.update", [$materium->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('nombre') ? 'has-error' : '' }}">
                            <label class="required" for="nombre">{{ trans('cruds.materium.fields.nombre') }}</label>
                            <input class="form-control" type="text" name="nombre" id="nombre" value="{{ old('nombre', $materium->nombre) }}" required>
                            @if($errors->has('nombre'))
                                <span class="help-block" role="alert">{{ $errors->first('nombre') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.materium.fields.nombre_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('curso') ? 'has-error' : '' }}">
                            <label for="curso_id">{{ trans('cruds.materium.fields.curso') }}</label>
                            <select class="form-control select2" name="curso_id" id="curso_id">
                                @foreach($cursos as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('curso_id') ? old('curso_id') : $materium->curso->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('curso'))
                                <span class="help-block" role="alert">{{ $errors->first('curso') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.materium.fields.curso_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/materia/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('materium_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.materia.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.materium.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.materium.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Materium">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.materium.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.materium.fields.nombre') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.materium.fields.curso') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($materia as $key => $materium)
                                    <tr data-entry-id="{{ $materium->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $materium->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $materium->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $materium->curso->nombre ?? '' }}
                                        </td>
                                        <td>
                                            @can('materium_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.materia.show', $materium->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('materium_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.materia.edit', $materium->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('materium_delete')
                                                <form action="{{ route('admin.materia.destroy', $materium->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('materium_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.materia.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Materium:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/materia/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('cruds.materium.title') }}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.materia.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>
                                        {{ trans('cruds.materium.fields.id') }}
                                    </th>
                                    <td>
                                        {{ $materium->id }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.materium.fields.nombre') }}
                                    </th>
                                    <td>
                                        {{ $materium->nombre }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.materium.fields.curso') }}
                                    </th>
                                    <td>
                                        {{ $materium->curso->nombre ?? '' }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.materia.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection